# Generated by Django 5.1.3 on 2025-04-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_code", models.CharField(max_length=8, unique=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("CS", "Casual"), ("TM", "Timed"), ("DQ", "Daily")],
                        max_length=2,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("current_question_index", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_quiz_sessions",
                        to="users.userprofile",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="joined_quiz_sessions", to="users.userprofile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                ("lifelines_used", models.JSONField(default=dict)),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.clue"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quizsession",
                    ),
                ),
            ],
        ),
    ]
