# Generated by Django 5.1.3 on 2025-04-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("BO", "Bollywood"),
                            ("MA", "Marathi"),
                            ("EN", "English"),
                        ],
                        max_length=2,
                    ),
                ),
                ("year", models.IntegerField()),
                ("poster", models.ImageField(upload_to="posters/")),
            ],
        ),
        migrations.CreateModel(
            name="Clue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clue_type",
                    models.CharField(
                        choices=[
                            ("IMG", "Image"),
                            ("DLG", "Dialogue"),
                            ("RDL", "Riddle"),
                        ],
                        max_length=3,
                    ),
                ),
                ("content", models.TextField()),
                ("difficulty", models.IntegerField(default=1)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
        ),
    ]
